llms:
  llama3.1:
    name: "@l"
    model: "llama3.1"
    url: "http://127.0.0.1"
    port: "11434"
    api_key: "${OLLAMA_LLAMA_API_KEY}"
    prompts:
      system: >
        You are a command-line assistant for Ubuntu 22.04. Your task is to convert natural language instructions into a single, precise shell command. Output only the command, nothing else. If no specific path is mentioned, assume the current directory.
      default: >
        Convert the following instruction into a single shell command for Ubuntu 22.04. Output only the command, no explanations:
    use_json: true

  phi3:
    name: "@p"
    model: "phi3"
    url: "http://127.0.0.1"
    port: "11434"
    api_key: "${OLLAMA_PHI_API_KEY}"
    prompts:
      system: >
        You are a command-line assistant for Ubuntu 22.04. Your sole purpose is to convert natural language instructions into a single, executable shell command. Respond with only the command, no explanations or additional text. If no specific path is mentioned, assume the current directory.
      default: >
        Convert this instruction into a single, executable shell command for Ubuntu 22.04. Respond with only the command:
    use_json: false

  anthropic:
    name: "@a"
    model: "claude-2"
    api_key: "${ANTHROPIC_API_KEY}"
    prompts:
      system: >
        You are a command-line assistant for Ubuntu 22.04. Your task is to convert natural language instructions into a single, precise shell command. Output only the command, nothing else. If no specific path is mentioned, assume the current directory.
      default: >
        Convert the following instruction into a single shell command for Ubuntu 22.04. Output only the command, no explanations:

  openai:
    name: "@o"
    model: "gpt-3.5-turbo"
    api_key: "${OPENAI_API_KEY}"
    prompts:
      system: >
        You are a command-line assistant for Ubuntu 22.04. Your task is to convert natural language instructions into a single, precise shell command. Output only the command, nothing else. If no specific path is mentioned, assume the current directory.
      default: >
        Convert the following instruction into a single shell command for Ubuntu 22.04. Output only the command, no explanations:

multi_model:
  dual_ollama:
    name: "@ml"
    models: ["llama3.1", "phi3"]
    decision_model: "llama3.1"
    decision_prompt: >
      Compare these shell commands and choose the most correct one for the instruction '{instruction}':
      {commands}
      Respond with only the number (1 or 2) of the best command, followed by '```' and the chosen command. For example:
      1
      ```ls -l```
      Do not provide any explanation or additional text.

  phi_llama:
    name: "@mp"
    models: ["phi3", "llama3.1"]
    decision_model: "phi3"
    decision_prompt: >
      Compare these shell commands and choose the most correct one for the instruction '{instruction}':
      {commands}
      Respond with only the number (1 or 2) of the best command, followed by '```' and the chosen command. For example:
      1
      ```ls -l```
      Do not provide any explanation or additional text.

  triple_mix:
    name: "@mix"
    models: ["llama3.1", "phi3", "anthropic"]
    decision_model: "openai"
    decision_prompt: >
      Compare these shell commands and choose the most correct one for the instruction '{instruction}':
      {commands}
      Respond with only the number of the best command, followed by '```' and the chosen command. For example:
      1
      ```ls -l```
      Do not provide any explanation or additional text.
